#Base image
FROM ubuntu:16.04
MAINTAINER deepika chamanagiri<deepika.chamanagiri@mindtree.com>

# Update APT Repo
RUN apt-get update

# Install Apache Packages
RUN apt-get install apache2 -y 

# Custom Index Page
RUN echo "HELLO WORLD.!!!" > /var/www/html/hello.html

# EXPOSE the PORT 
EXPOSE 80

# Start Apache Service
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
